### ISSUE TITLE
What's the current state?

### ISSUE THREAD

**Issue by baptisteArno** [awesome-selfhosted/awesome-selfhosted-data#11]
I find that it's not clear what is the state of this repo? What needs to be done still?

How can I help?

**Comment by baptisteArno** [comment]
Any plan to also enrich the data?

Right now I can think of: `images`, `icon`, `alternative-to` (lots of people are searching for OS alternatives)

What are your thoughts about this?

**Comment by nodiscc** [comment]
Automatic HTML and markdown exports are now working properly. This repo will become the upstream source for awesome-selfhosted in the coming days.

Feel free to continue this discussion in https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/33 which has more details on remaining tasks.
