### ISSUE TITLE
Only render project descriptions in search results

### ISSUE THREAD

**Issue by mechanarchy** [awesome-selfhosted/awesome-selfhosted-data#116]
# Problem statement
I tried searching for `link` and all the results just gave me HTML excerpts:
https://awesome-selfhosted.net/search.html?q=link&check_keywords=yes&area=default
> ![image](https://github.com/awesome-selfhosted/awesome-selfhosted-data/assets/1166756/f5a59b35-e711-4fc6-a649-c2a34062031d)

I tried searching for a specific project that I know is listed, `monica`
https://awesome-selfhosted.net/search.html?q=monica&check_keywords=yes&area=default
Even then the results don't show HTML excerpts, but the result text is kinda mangled with a lot of irrelevant values (star count, language tags, HTML link text without the `href` etc).
> ![image](https://github.com/awesome-selfhosted/awesome-selfhosted-data/assets/1166756/e3550df3-d221-4b06-a985-b162d2c2781f)

# Desired behaviour
I'm not sure how the search code operates, but ideally I would like to see just the project description first. If possible, formatting the results with HTML to show the tags/links/star count etc would be nice, but nowhere near necessary if the HTML problem above can be fixed

**Comment by nodiscc** [comment]
Hi @mechanarchy 
What would be the expected result?

**Comment by nodiscc** [comment]
> 'm not sure how the search code operates

The website is rendered by [Sphinx](https://www.sphinx-doc.org/en/master/index.html). Sphinx builds a full-text index of all documents, and the search functionality uses this index.

Sphinx's search functionality only has single relevant configuration setting: [html_show_search_summary](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_show_search_summary). Setting this to `False` disables inclusding snippets in the search results:

![image](https://github.com/awesome-selfhosted/awesome-selfhosted-data/assets/3950390/c43e7f2d-cbc8-483a-b9a0-462835606ee1)

So unless I missed something, changing the way search results are displayed would require implementing changes in Sphinx directly, or [writing an extension](https://www.sphinx-doc.org/en/master/development/index.html). I'm unlikely to work on that, but if someone writes such an extension I would add it to our sphinx configuration.

As a workaround, you can use your web browser's search feature on the index page (`Ctrl+F monica`, `Ctrl+F link`...)

**Comment by nodiscc** [comment]
However I think we can prevent the inline CSS from showing up in the search results, by moving it to an external .css file.

**Comment by nodiscc** [comment]
> we can prevent the inline CSS from showing up in the search results, by moving it to an external .css file.

Fixed in #262
