### ISSUE TITLE
Medusajs broken demo link 

### ISSUE THREAD

**Issue by OscarTyrberg** [awesome-selfhosted/awesome-selfhosted-data#172]
Proposing to change the currently broken "demo" link for Medusajs to this link instead: https://medusajs.com/nextjs-commerce/

It is a new Nextjs starter that allows to quickly setup and deploy a storefront using Medusa. 

//Oscar, Business Analyst at Medusajs

**Comment by nodiscc** [comment]
I suggest using https://next.medusajs.com/ instead.

@OscarTyrberg would you like to send a pull request that fixes the URL in https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/medusajs.yml#L11 ?

(Related https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/173)

**Comment by OscarTyrberg** [comment]
Would love to include the starter in the list some way, but could also add it as a software on its own if that makes more sense? 

I am no dev myself, so have no experience of doing pull request, hence why starting a new issue as this was an option in the "contributing" file. Would it be doable without me creating a pull request? Thanks

**Comment by nodiscc** [comment]
Fixed in https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/175
