### ISSUE TITLE
Hoppscotch is currently listed multiple times

### ISSUE THREAD

**Issue by Rabenherz112** [awesome-selfhosted/awesome-selfhosted-data#205]
Currently, there are two instances of Hoppscotch listed in the software section.
One as [hoppscotch-community-edition.yml](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/hoppscotch-community-edition.yml) and the other one as [hoppscotch.yml](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/hoppscotch.yml)

Both instances are identical in content. I noticed that @nodiscc made some changes recently (https://github.com/awesome-selfhosted/awesome-selfhosted-data/commit/de06a1837fcf9e26a057f40f910d9261b041f970), is this intentional?

**Comment by KieranRobson** [comment]
I'd assume that hopscotch.yml would be the correct version due to other community editions just having the single software name as the file name.

**Comment by nodiscc** [comment]
>  is this intentional?

No it's not -> https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/208 fixes this.

Thanks for noticing.
