### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by hasecilu** [awesome-selfhosted/awesome-selfhosted-data#237]
Should be TypeScript be added or use JavaScript instead?
I used Typescript on #235  and #236

**Comment by KieranRobson** [comment]
It's likely that neither should be used and instead Nodejs should be used.

**Comment by nodiscc** [comment]
If `npm` is used to install the software, `Nodejs` should be used.

> Values for platform are the main server-side requirements for the software. Don't include frameworks or specific dialects.

**Comment by hasecilu** [comment]
Ok, thanks for the clarification.
