### ISSUE TITLE
Thoughts on non-English additions

### ISSUE THREAD

**Issue by Ki-er** [awesome-selfhosted/awesome-selfhosted-data#251]
I found https://github.com/acp-admin/acp-admin/ while working on a PR.

As you can see the instructions are not in English. Are we allowing non-English additions in this list?

**Comment by nodiscc** [comment]
I think it used to be allowed (see https://github.com/awesome-selfhosted/awesome-selfhosted/pull/893, https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3357) - but adding `(documentation in French)` to the description would be nice.
