### ISSUE TITLE
Workflow update-metadata breaks when a GitHub Repository doesn't exists

### ISSUE THREAD

**Issue by Rabenherz112** [awesome-selfhosted/awesome-selfhosted-data#27]
The workflow update-metadata encounters an issue when a GitHub repository does not exist. This problem results in the job being halted and further checks not being performed.

Expected output:
https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions/runs/5205347247/jobs/9390696384

Actual output:
https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions/runs/5216295216/jobs/9414872295

**Comment by nodiscc** [comment]
Thanks for taking the time to report this.

Fixed in https://github.com/awesome-selfhosted/awesome-selfhosted-data/commit/ce136cf4773eeb851787bfe93031d488dcb61af4, metadata updates and URL checks now run independently, in parallel https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions/runs/5284187401.

**Comment by Rabenherz112** [comment]
Sorry to annoy you again, but are you sure that the action works now (for me, it looks like it now broke completely)
https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions/runs/5284187401/jobs/9561352646#step:2:8

**Comment by nodiscc** [comment]
Not annoying at all, thank you for the report.

> are you sure that the action works now

It didn't, I had only checked that jobs were being run in parallel - but the url_check job was missing a checkout step - added in https://github.com/awesome-selfhosted/awesome-selfhosted-data/commit/c7e09df4811b0579fcfcfd3d69fe9402229efdcf -> problem fixed https://github.com/awesome-selfhosted/awesome-selfhosted-data/actions/runs/5289713083

Also made it possible to trigger the workflow manually at any time, without waiting for the time set in the cron expression (https://github.com/awesome-selfhosted/awesome-selfhosted-data/commit/9345d7c8837914a3434684780652c2c92a23d994).
