### ISSUE TITLE
Is there a duplicate item of Hoppscotch?

### ISSUE THREAD

**Issue by razonyang** [awesome-selfhosted/awesome-selfhosted-data#341]
Hi, are those two item are same?
- https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/hoppscotch-community-edition.yml
- https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/hoppscotch.yml

**Comment by nodiscc** [comment]
Yes, they are. I will remove `hoppscotch.yml`. Thank you for reporting this.
