### ISSUE TITLE
add placeholder for event invite software

### ISSUE THREAD

**Issue by meonkeys** [awesome-selfhosted/awesome-selfhosted-data#343]
I'm having trouble finding any good self-hosted software for managing a small event: guests, emails, event description, RSVPs, stuff like that. What do you think about adding a placeholder section?

I did find *one* that looks decent if we don't want to start with a completely empty category: https://wordpress.org/plugins/rsvp/

Here are some more sorta leads:

* https://www.reddit.com/r/selfhosted/search/?q=evite&restrict_sr=1
* https://www.reddit.com/r/selfhosted/comments/eqddfy/party_rsvp_replacement_for_evitepunchbowl/
* https://www.reddit.com/r/selfhosted/comments/543gmg/alternative_to_evite_or_anyvite/
* https://www.reddit.com/r/selfhosted/comments/m5pdgg/selfhosted_weddingevent_rsvp_page/
* https://www.reddit.com/r/selfhosted/comments/8c46wf/facebook_event_alternative/
* https://www.reddit.com/r/selfhosted/comments/558i8l/birthdayrsvp_website/
* http://davite.com
* https://sourceforge.net/projects/weddinginvites/

**Comment by nodiscc** [comment]
Hi,

I think this would belong in https://awesome-selfhosted.net/tags/polls-and-events.html. There is already similar software there (_Enables organizers to manage events from concerts to conferences and meet-ups._, etc.).

In addition, it's not possible to add a placeholder section or a section with only 1 item (https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/CONTRIBUTING.md#add-a-tagcategory)

> Tags represent functional categories/features of the software, and must be added to tags/tag-name.yml (use [existing tags](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/tags) as example). Any tag must have a minimum of 3 software projects referencing it. The [Miscellaneous](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/tags/miscellaneous.yml) tag can be used for software not matching any existing category.

**Comment by meonkeys** [comment]
Thanks and thanks! Perfect, I'll take a look at all this.
