### ISSUE TITLE
Label 'fix' doesn't exist anymore

### ISSUE THREAD

**Issue by Rabenherz112** [awesome-selfhosted/awesome-selfhosted-data#486]
Just a heads up, the `fix` label we used to use in our ['old' awesome-sefhosted](https://github.com/awesome-selfhosted/awesome-selfhosted/pulls?q=is%3Apr+label%3Afix+is%3Aclosed) repo doesn't exist in here anymore.
However in [CONTRIBUTING.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/CONTRIBUTING.md#contributing) , it still calls it `fix` rather than `bug`. (That's the reason why when you click on it, you end up seeing nothing)

Should we rename the `bug` label, or tweak our contributing guidelines?

**Comment by nodiscc** [comment]
Thanks for reporting this. I updated the documentation to mention `bug` instead of `fix`, so that we can also use it to report plain bugs or incorrect data, as well as provide fixes.
