### ISSUE TITLE
Update PR Template to Account for Updates

### ISSUE THREAD

**Issue by ryangurn** [awesome-selfhosted/awesome-selfhosted-data#538]
I have been submitting quite a few PRs in the past couple days to update tags, urls and some other incorrect values I have noticed while going through the list of software. 

It would be nice if we update the PR template to take into account updates rather than just additions so we can more easily track the tasks needed for major or minor updates. 

I am more than willing to submit a PR once I know if you all are open to changing the template and we have an idea of what the changes/tasks would be in the PR template.

I am thinking something like the following:
```markdown
Thanks for taking the time to contribute to awesome-selfhosted! 

<!-- DO NOT DELETE THE TEXT BELOW if you are ADDING new software to the list. Please make sure relevant boxes are checked [x] -->

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [ ] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [ ] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [ ] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [ ] Comments and unused optional fields have been removed.
- [ ] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [ ] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [ ] Any software project you are adding has working installation instructions.
- [ ] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.

<!-- DO NOT DELETE THE TEXT BELOW if you are UPDATING new software to the list. Please make sure relevant boxes are checked [x] -->

To ensure your Pull Request is dealt with swiftly, please check the following (check the boxes `[x]`):
- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [ ] The file you are adding is formatted as described in [addition.md](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.github/ISSUE_TEMPLATE/addition.md).
- [ ] All links are still valid and accessible
- [ ] `Demo` links should only be used for interactive demos, i.e. not video demonstrations. 
- [ ] Comments and unused optional fields have been removed.
- [ ] The file you are adding uses [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case) file naming, for example `my-awesome-software.yml`.
- [ ] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [ ] Any software project you are updating is still actively maintained.
- [ ] Any software project you are updating has had a tagged release within the past year.
- [ ] You understand that your Pull Request will be merged ~1 week after approval, to allow for further comments if needed.
```

**Comment by nodiscc** [comment]
I think the PR checklist is already intimidating to new contributors, expanding it would make it worse (even though they just have to delete the lower part, that's still one more thing to do/understand and will discourage people).

Unfortunately Github doesn't allow multiple PR templates (e.g one for additions, one for updates, one for cleanup of old projects, etc.) It is possible for issues (when `New Issue` is clicked it shows a nice list allowing you to select the template), but not for PRs. Worth noting that Gitlab and Gitea-and-likes do have this feature.

- [ ] The correct thing to do when updating or removing an entry is to just **delete** the placeholder/checklist. I think we should make this clearer.

See also https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/33#issuecomment-1902091406 where a possible "contributor guide"/FAQ is discussed.

By the way, thank you for your help with maintenance these last days.

**Comment by ryangurn** [comment]
> Unfortunately Github doesn't allow multiple PR templates (e.g one for additions, one for updates, one for cleanup of old projects, etc.) It is possible for issues (when `New Issue` is clicked it shows a nice list allowing you to select the template), but not for PRs. Worth noting that Gitlab and Gitea-and-likes do have this feature.

I found this out yesterday and could not believe github lacks support for multiple PR templates. 

It makes plenty of sense that we do not want to add complexity to the PR process.

**Comment by nodiscc** [comment]
Proposed fix in https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/542
