### ISSUE TITLE
Submitted software not showing up

### ISSUE THREAD

**Issue by guchenhe** [awesome-selfhosted/awesome-selfhosted-data#543]
I submitted Dify.AI via #407 last month, but it's not showing up on the website.

**Comment by guchenhe** [comment]
![CleanShot 2024-01-27 at 19 38 17@2x](https://github.com/awesome-selfhosted/awesome-selfhosted-data/assets/13230914/71638e81-e9ba-4021-a9db-fcfb1f999fd7)
Seems like the mismatch between yaml filename and the software name might have led to bot generating a new file. If this is the issue maybe deleting `dify.yml` would work.

**Comment by nodiscc** [comment]
It is showing, on the Non-Free page (due to the `Commons-Clause` license): https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md#software-development---low-code

However there are 2 files `dify.ai.yml` and `dify.yml` so it is duplicated. I will clean this up.
