### ISSUE TITLE
duplicate definition of OpenTrashmail

### ISSUE THREAD

**Issue by cu** [awesome-selfhosted/awesome-selfhosted-data#559]
I'm not sure how it's happening, but OpenTrashmail appears twice in the main repo:

![image](https://github.com/awesome-selfhosted/awesome-selfhosted-data/assets/529168/f53f4481-c2b2-4a55-be76-3d8481000183)

**Comment by nodiscc** [comment]
Thank you for taking the time to report this.
Fixed in https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/561
