### ISSUE TITLE
MailCare is abandoned, new version will be closed-source

### ISSUE THREAD

**Issue by nogweii** [awesome-selfhosted/awesome-selfhosted-data#581]
See https://gitlab.com/mailcare/mailcare/-/issues/29#note_1761882715:

> I am currently developing a new version of MailCare. However, it will no longer be open-source, I apologize for this change. Consequently, I will not be updating the documentation.

Remove it for now? Or move it to non-free?

**Comment by nodiscc** [comment]
Hi, I don't know if this single comment should trigger the removal of Mailcare from the list (the current source code is still there after all). However

>https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/CONTRIBUTING.md#curation
> Software with no development activity for 6-12 months may be removed from the list

Let's remove it as soon as it reaches the 6 month threshold (March 27 2024 https://gitlab.com/mailcare/mailcare/-/commits/master/?ref_type=HEADS)

Thanks for the heads-up
