### ISSUE TITLE
Duplicate entry: ZOT OCI Registry

### ISSUE THREAD

**Issue by DeKleineKobini** [awesome-selfhosted/awesome-selfhosted-data#596]
ZOT OCI Registry is listed twice. One of them should be deleted.

* [zotregistry.yml](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/zotregistry.yml)
* [zot-oci-registry.yml](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/zot-oci-registry.yml)

**Comment by kokomo123** [comment]
i did look for zot to make sure it wasn't a duplicate when creating this PR iirc, but thank you! I shall make a PR to remove the duplicate
