### ISSUE TITLE
GitHub Actions run on Forks

### ISSUE THREAD

**Issue by Rabenherz112** [awesome-selfhosted/awesome-selfhosted-data#60]
For quite some time now, I've been receiving notifications about failed pipelines. These notifications are being triggered because the jobs are currently running on forks as well. 

![2023-08-18-12-01_271](https://github.com/awesome-selfhosted/awesome-selfhosted-data/assets/66558576/387022de-5ea7-4a77-bdfc-2f3069caa7a7)

While it's possible for me to simply disable all actions on the forked repository by navigating to Settings > Actions > Actions permissions and choosing "Disable Actions for this repository," I believe this solution is not ideal, as it would require every user who contribute to this project to perform this manual step individually.

Fortunately, GitHub provides a solution template to address this issue. The problem could be easily resolved by implementing an if condition, as demonstrated in the example provided in GitHub's documentation on workflow syntax for GitHub Actions:
[GitHub Actions Workflow Syntax Example](
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository)

It might be worth considering this approach before making this repo the new main awesome-selfhosted repo.

**Comment by nodiscc** [comment]
Thank you for reporting this. I will apply the fix you suggested.

**Comment by nodiscc** [comment]
Done in https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/62

> the jobs are currently running on forks as well.

Strange, I do not get the same behavior when I fork the repo to my personal account. For me all workflows seem to be disabled by default, clicking on the `Actions` tab asks me to enable them manually:

![image](https://github.com/awesome-selfhosted/awesome-selfhosted-data/assets/3950390/509f5b49-e05f-4447-af16-e39bc1708fe2)
