### ISSUE TITLE
Keepass available via WebDAV and SFTP 

### ISSUE THREAD

**Issue by artk42** [awesome-selfhosted/awesome-selfhosted-data#624]
desktop+web clients: KeepassXC / Keeweb / Strongbox works with WebDAV and SFTP self-hosted databases in a totally open standard. It is self-hosted in more ways than alternatives.

**Comment by nodiscc** [comment]
Hi, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/224#issuecomment-1742175080 and linked issues.

> Following this logic, any program that produces files which can be published through a web server (LibreOffice can write HTML files), or shared through a file synchronization system would qualify. You can find many precedents [here](https://github.com/awesome-selfhosted/awesome-selfhosted/issues?q=is%3Aissue+label%3Ainvalid+is%3Aclosed).

**Comment by artk42** [comment]
Okay, got the logic - no server software = no self-hosted criteria met. Databases don't count. In that manner, though it is unclear if the name of repo "[awesome-selfhosted-data](https://github.com/awesome-selfhosted/awesome-selfhosted-data)" meets the aforementioned criteria at all or just a bit confusing.

It seems that the ability to control the full chain of storage of the sensitive (like in the case of KeePass) is an aim of self-hosting, while statically storing data employing simplification and common network protocols, is a reasonable way of avoiding unnecessary overhead to meet an aim, rather than downward of meeting the "server" criteria.
