### ISSUE TITLE
Duplicate entries: motion.tools, OpenSlides, ZOT OCI Registry and Tiny File Manager

### ISSUE THREAD

**Issue by Surrogard** [awesome-selfhosted/awesome-selfhosted-data#700]
I found 4 duplicate tools:
* motion.tools
  * `software/motion.tools-antragsgrün.yml` (contains more metadata)
  * `software/motion-tools.yml`
* OpenSlides
  * `software/open-slides.yml`
  * `software/openslides.yml` (contains more metadata)
* ZOT OCI Registry
  * `software/zot-oci-registry.yml` (contains more metadata)
  * `software/zotregistry.yml`
* Tiny File Manager (already being discussed [here](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/697) )
  * `software/tiny-file-manager.yml` (contains more metadata)
  * `software/tinyfilemanager.yml`

**Comment by Rabenherz112** [comment]
Thanks for reporting this!
