### ISSUE TITLE
Filter whole list to show only specific platforms/languages

### ISSUE THREAD

**Issue by crispybegs** [awesome-selfhosted/awesome-selfhosted-data#71]
as requested by maintainer on reddit.
i'd love a way of being able to filter the whole list to show only those services / apps that have docker containers, since that's how I implement everything

thanks!

**Comment by nodiscc** [comment]
I can see this being useful (e.g someone wanting to manage their entire setup through Docker, or shared hosting users looking for PHP projects...).

The easiest way would be creating a sub-page for each language/platform (similar to how we currently have a subpage for each tag/category). This would need to be implemented in https://github.com/nodiscc/hecat/blob/master/hecat/exporters/markdown_multipage.py

I don't think these sub-pages should be added to the sidebar (cluttering it), however the language tags in the list itself should be made clickable, and link to the corresponding platform/language sub-page.

A special page `All platforms` can also be made available with a link to all platform/language sub-pages.

**Comment by nodiscc** [comment]
Someone at https://old.reddit.com/r/selfhosted/comments/15y7y36/the_awesomeselfhosted_repo_released_a_new_website/ mentioned that it would be useful to have the ability to search for programs that have ready-made Arm binaries available (though [which Arm?](https://nickdesaulniers.github.io/blog/2023/03/10/disambiguating-arm/)).

We could add `Arm` as a platform, and a sub-page would be built, only listing items which match this platform.

**Comment by KieranRobson** [comment]
> We could add Arm as a platform, and a sub-page would be built, only listing items which match this platform.

This seems like the best option, this way we dont need to have different `Arm` platforms and it is more generic for someone who is just browsing for `arm` projects

**Comment by ShakataGaNai** [comment]
Maybe Kubernetes as well? Obviously, if it's dockerized it CAN be run in K8s, but sometimes it can be quite complex if there is no documentation or examples.

**Comment by nodiscc** [comment]
To be clear, this would include any platform listed in https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms, so k8s as well.

**Comment by cpdeethree** [comment]
> Maybe Kubernetes as well? Obviously, if it's dockerized it CAN be run in K8s, but sometimes it can be quite complex if there is no documentation or examples.

Let's be more clear than that, if it's dockerized it can, but if it's an orchestration of containers (e.g. docker-compose) you will need the k8s equivalent which is usually either a Kustomize manifest or a Helm chart (rather than a series of disparate yaml files)

**Comment by nodiscc** [comment]
There is now a subpage for each `platform` (e.g. https://awesome-selfhosted.net/platforms/docker.html). You can navigate between platforms by clicking on the relevant icon/field in each project's metadata.

![image](https://github.com/awesome-selfhosted/awesome-selfhosted-data/assets/3950390/f6de6a7b-23bc-4d1b-affe-590279a69e2e)

If you think a list of all platforms is needed somewhere, please open a new issue. Please include you thoughts on how/where this list should be displayed, as we shouldn't clutter the sidebar by mixing `tags` and `platforms` there.

> I'd love to filter out services that require docker

You can do so by browsing the page for any other platform (e.g. https://awesome-selfhosted.net/platforms/php.html) - projects that **require** docker are normally tagged **only** with `Docker`.
