### ISSUE TITLE
[Feature request] Add filters to page

### ISSUE THREAD

**Issue by Nriver** [awesome-selfhosted/awesome-selfhosted-data#78]
Congratulations on the new website!

I think it would be nice to have a filter on the main page.

For example, the star count. Let's say I'm only interested in projects that have over 1000 stars, which usually means that they are tested more and are probably more stable for production. Alternatively, someone may like projects with less than 100 stars, which means more opportunity to contribute to software in an early stage.

It would also be nice to have a language filter, license type filter, etc.

**Comment by nodiscc** [comment]
> Let's say I'm only interested in projects that have over 1000 stars

Wontfix, as discussed in other issues, github stars are not a useful metric (moreover 100 is an arbitrary threshold, what about 10000? 10? 50?). Moreover the current tooling for the site (static site generated by sphinx) does not allow us to implement this without a mjor refactoring.

The data stays available under CC-BY-SA license, so feel free to implement this in a separate project (compliant with the license, notably attribution), which could be listed in https://awesome-selfhosted.net/#external-links.

The most important filter (language/platform filter) has been implemented. Feel free to reopen separate issues for specific filters.
