### ISSUE TITLE
Open links in a new tab

### ISSUE THREAD

**Issue by desk7** [awesome-selfhosted/awesome-selfhosted-data#842]
I suggest to add the "_blank" target attribute to "Website" and "Source Code" links.

**Comment by Rabenherz112** [comment]
Hey there, we already had a similar discussion here https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/33#issuecomment-1694680794 , where we concluded that by not adding a blank tag; we let it open to every user if they want it to open in a new tab or not.
