### ISSUE TITLE
Please remove my email address from AUTHORS.md

### ISSUE THREAD

**Issue by pengc99** [awesome-selfhosted/awesome-selfhosted-data#896]
Please remove my email address from AUTHORS.md or replace it with a placeholder.

**Comment by nodiscc** [comment]
Hi @pengc99 unfortunately we cannot do that, as AUTHORS.md is generated from the `git log`

See also https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2580 (I think there was another such case).

The only solution would be overriding your e-mail using a placeholed in https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/.mailmap (which would then contain your email address). Let me know if you'd prefer that.

**Comment by pengc99** [comment]
sure, I totally understand the difficulty of this, let's go with your option
