### ISSUE TITLE
Add solidtime

### ISSUE THREAD

**Issue by korridor** [awesome-selfhosted/awesome-selfhosted-data#925]
I opened a PR for the addition of solidtime, but it was closed due to not being mature enough.
Since time has passed now and the first release is now more than 4 months ago, I wanted to ask if you could look at the PR again.

You can find the PR here: #808

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.

**Comment by Rabenherz112** [comment]
Closed with commit https://github.com/awesome-selfhosted/awesome-selfhosted-data/commit/691f7739accee37d67ae2bb0b2b498efffeb52bc
