### ISSUE TITLE
Wrong source code url and duplicate entries

### ISSUE THREAD

**Issue by bntti** [awesome-selfhosted/awesome-selfhosted-data#966]
## Duplicate entries

- Beaver Habit Tracker
  - `software/beaver-habit-tracker.yml` (contains more metadata)
  - `software/beaverhabits.yml`
- Discount Bandit
  - `software/discount-bandit.yml` (contains more metadata)
  - `software/discountbandit.yml`
- Pelican Panel
  - `software/pelican-panel.yml` (contains more metadata)
  - `software/pelicanpanel.yml`
- Vvveb CMS
  - `software/vvveb-cms.yml` (contains more metadata)
  - `software/vvveb.yml`

## Wrong source code URL

The source code URL for `software/traefik.yml` is https://github.com/static-web-server/static-web-server when it should probably be https://github.com/traefik/traefik

**Comment by Rabenherz112** [comment]
Hey there, massive thanks for reporting the issues. Highly appreciated!

**Comment by nodiscc** [comment]
Thanks @bntti for the report, thanks @Rabenherz112 for the fix
I've made a note to check for duplicate names across all items during automated checks https://github.com/nodiscc/hecat/issues/141
