### ISSUE TITLE
Is Tandoor really Non-Free?

### ISSUE THREAD

**Issue by markalex2209** [awesome-selfhosted/awesome-selfhosted-data#994]
Currently Tandoor is listed as Non-Free software on the list: [tandoor-recipes.yml](https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/tandoor-recipes.yml), [recipe-management](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md#recipe-management).

I'm no expert on their license and/or pricing model, but it looks to me as if they take money only from users of the hosted instance.
On the other hand, self-hosted version, which I guess main/only(?) focus of this project, is completely free and fully functional.

Is the placement of the Tandoor in Non-Free list mistake, or have I misunderstood criteria of being put there?

**Comment by nodiscc** [comment]
Hi,

Tandoor uses the "Commons Clause" condition in its license file
- https://github.com/TandoorRecipes/recipes/blob/develop/LICENSE.md
- https://commonsclause.com/

> the License does not grant to you, the right to Sell the Software.

This makes the software "source-available" but not Free and Open-Source https://en.wikipedia.org/wiki/Source-available_software#Commons_Clause

> https://opensource.org/osd
> The license shall not restrict any party from selling or giving away the software
